#!/usr/bin/env python3
"""
Interactive script to setup Reddit API credentials
"""

import os
import getpass

def setup_credentials():
    """Interactive setup for Reddit API credentials."""
    print("=" * 60)
    print("REDDIT API CREDENTIALS SETUP")
    print("=" * 60)
    print("\nBefore continuing, make sure you have:")
    print("1. Gone to https://www.reddit.com/prefs/apps")
    print("2. Created a new 'script' app")
    print("3. Noted your Client ID and Client Secret")
    print("\n" + "=" * 60)
    
    proceed = input("\nHave you completed the above steps? (y/n): ").strip().lower()
    if proceed not in ['y', 'yes']:
        print("Please complete the Reddit app setup first, then run this script again.")
        return False
    
    print("\nEnter your Reddit API credentials:")
    
    # Get Client ID
    client_id = input("Client ID (short string under app name): ").strip()
    if not client_id or client_id == "your_client_id_here":
        print("❌ Invalid Client ID")
        return False
    
    # Get Client Secret
    client_secret = getpass.getpass("Client Secret (longer secret string): ").strip()
    if not client_secret or client_secret == "your_client_secret_here":
        print("❌ Invalid Client Secret")
        return False
    
    # Get Username
    username = input("Reddit Username: ").strip()
    if not username:
        print("❌ Username is required")
        return False
    
    # Get Password
    password = getpass.getpass("Reddit Password: ").strip()
    if not password:
        print("❌ Password is required")
        return False
    
    # Create user agent
    user_agent = f"RedditScraper/1.0 by {username}"
    
    # Write to .env file
    env_content = f"""# Reddit API Credentials
# Generated by setup_credentials.py
REDDIT_CLIENT_ID={client_id}
REDDIT_CLIENT_SECRET={client_secret}
REDDIT_USER_AGENT={user_agent}

# Reddit Login Credentials (for higher rate limits)
REDDIT_USERNAME={username}
REDDIT_PASSWORD={password}
"""
    
    try:
        with open(".env", "w") as f:
            f.write(env_content)
        
        print("\n✓ Credentials saved to .env file")
        print("✓ Setup completed successfully!")
        return True
        
    except Exception as e:
        print(f"❌ Failed to save credentials: {e}")
        return False

def main():
    """Main function."""
    if setup_credentials():
        print("\n" + "=" * 60)
        print("🎉 READY TO USE!")
        print("=" * 60)
        print("\nYou can now run the scraper:")
        print("1. Interactive mode: python run_scraper.py")
        print("2. Command line: python reddit_scraper.py \"your keywords\"")
        print("=" * 60)
    else:
        print("\n❌ Setup failed. Please try again.")

if __name__ == "__main__":
    main()